### ISSUE TITLE
Modal windows on the players screen should always show the entire image of a shared handout

### ISSUE THREAD

**Issue by havok2905** [havok2905/dm-screen#57]
When you share a handout to the player's view page it shows in a modal. If the image is too big for the modal, the image cuts off to allow for scrollable content. This works great for stat blocks and long form content, but we always want to show a player the full image we are displaying.

I think this may happen in a few stages:

Stage 1 ( This issue )

- Add option to modal to be a larger size and not scrollable -> perhaps something like a `isShowcaseView` prop
- Images scale to the full width or height of the container to fit

Stage 2 ( Future Issue )

- Modals could be smart and expand to the natural size of the content passed to them.

**Comment by wizzah** [comment]
This option for the modal to be a larger size, is there a place in the app where the modal content is editable?

**Comment by wizzah** [comment]
addressed in https://github.com/havok2905/dm-screen/pull/69
