### ISSUE TITLE
SPIKE - Populate this project with new batch of tickets

### ISSUE THREAD

**Issue by havok2905** [havok2905/dm-screen#62]
Use this list

- Expanded Rules drawer
- Player Admin Pages ( For repeat players )
    - Players Page
    - Player Page ( Navigate from Adventures Page )
    - Player Create Page
    - Player Edit Page
- Conditions for initiative players -> propegated to initiative cards
    - Death save successes
    - Death save failures
- Marked extension to make attack actions clickable and roll
- Marked extension to make creature and item names link to their respective pages
- More aesthetically pleasing dice roller
- Extra commands for toolbar footer
    - Start Combat
    - End Combat
    - Roll Initiative for all
    - Roll initiative for creatures
    - Sort initiative
- Toolbar footer command history and traversal
- Player’s Screen Preview display

Technical Improvements

- Introduce Cypress e2e tests
- Build test DB seeds for e2e tests

Potential Bugs/Enhancements

- Adventure drawer should preserve scroll position
- Scroll to top button in footer -> quickly snap to initiative

**Comment by wizzah** [comment]
Just curious, why cypress for e2e tests?

**Comment by havok2905** [comment]
Mostly because work uses it and I want to understand it more deeply. I'm open to other e2e test frameworks though.
