### ISSUE TITLE
Add form validation to player managerment form in dm-view

### ISSUE THREAD

**Issue by havok2905** [havok2905/dm-screen#66]
Bring in https://react-hook-form.com/ and flesh out form validation on the player management modal. This is overkill for player management, but will be more useful when it comes time to flesh out admin pages for creating/editing adventures, items, creatures, etc.

Elevated to P0, as this is a blocker for other page level issues, like adventure admin pages.

**Comment by wizzah** [comment]
I don't think I have the power to move this into "in progress", so this is spiritually in progress!

**Comment by wizzah** [comment]
Relevant PR - https://github.com/havok2905/dm-screen/pull/79
